### PR TITLE
Remove ROOT_MOUNT_MASTER status

### LINKED ISSUE #147: Version 5.0.4 not work for Virtual Machine like VMOS and VPhoneGaga, please check and fix it
All Shell Code (except Grant Root Permission) not work for Virtual Machine for libsu with version 4.0.0 and above, but version 3.2.1 work fine, please check it and fix it ! ! !

even code like `Shell.isAppGrantedRoot()` always return `FALSE`

### LINKED ISSUE #157: Remove ROOT_MOUNT_MASTER status
https://github.com/topjohnwu/libsu/blob/c9f1a6e7a5c11aa3b83eeadb8abf616d47dac049/core/src/main/java/com/topjohnwu/superuser/internal/ShellImpl.java#L164-L166

We can't be sure that `readlink /proc/1/ns/mnt` command will return content. If the standard output has no content (maybe in error output, or nothing at all), then `readLine()` will block.

https://github.com/topjohnwu/Magisk/blob/4856da1584c16f5c7387efcefe255c21a1978233/native/src/core/su/su.cpp#L38
```
    "  -t, --target PID              PID to take mount namespace from\n"
```

MagiskSU now supports setns, this check has lost its meaning. I don't think anyone really cares about state other than root, so this check can be removed. libsu should do as little as possible and leave any additional requirements to the developers themselves.

### PR DESCRIPTION
**Pull request by vvb2060**
close #157, fix #147, fix topjohnwu/Magisk#7021

### CODE REVIEW

File: core/src/main/java/com/topjohnwu/superuser/Shell.java [hunk 1]
```diff
@@ -77,15 +77,15 @@ public abstract class Shell implements Closeable {
...
     public static final int ROOT_SHELL = 1;
     /**
-     * Shell status: Root shell with mount master enabled.
-     * One possible result of {@link #getStatus()}.
+     * @deprecated Not used anymore.
      * <p>
      * Constant value {@value}.
      */
+    @Deprecated
     public static final int ROOT_MOUNT_MASTER = 2;
```
Comment (yujincheng08) [inline core/src/main/java/com/topjohnwu/superuser/Shell.java:85]:
```suggestion
```

Comment (topjohnwu) [reply core/src/main/java/com/topjohnwu/superuser/Shell.java:85]: The value should be preserved to prevent code breakage

**Review by topjohnwu — APPROVED** [review]
